### ISSUE TITLE
Using Vue.component throws an error

### ISSUE THREAD

**Issue by StefanT123** [fusioncharts/vue-fusioncharts#20]
When I try to use
```
import VueFusionCharts from 'vue-fusioncharts';
import FusionCharts from 'fusioncharts/core';
import MSLine from 'fusioncharts/viz/msline';

Vue.component('fusioncharts', VueFusionCharts, FusionCharts, MSLine);
```
in my component, in the console.log I have an error:
![image](https://user-images.githubusercontent.com/28436358/45409140-a672cf80-b66e-11e8-8b9f-de288c3913cb.png)

The error is pointing in the node-modules\vue-fusioncharts\src\index.js in the install function:
```
const install = (Vue, FC, ...options) => {
    options && options.forEach && options.forEach((modules) => {
        addDep(FC, _FC, modules);
    });
    let component = _FCComponent(FC);

    Vue.component(component.name, component);
};
```
Also when I console.log the Vue.component in the install function it says that it's undefined:
```
const install = (Vue, FC, ...options) => {
    options && options.forEach && options.forEach((modules) => {
        addDep(FC, _FC, modules);
    });
    let component = _FCComponent(FC);
    console.log('vue-fusioncharts', Vue.component); // my console.log
    Vue.component(component.name, component);
};
```
![image](https://user-images.githubusercontent.com/28436358/45409430-695b0d00-b66f-11e8-8862-5774c41c48cd.png)

Another problem is that when I try to import { FCComponent }, the npm can't find it.
`import { FCComponent } from 'vue-fusioncharts';`
![image](https://user-images.githubusercontent.com/28436358/45409635-0c138b80-b670-11e8-8ca8-d3a6efb6e35f.png)

**Comment by ashok1994** [comment]
did you try using it as a plugin , Vue.use(VueFusionCharts, FusionCharts, ...otherDependencies)

**Comment by StefanT123** [comment]
> did you tried using it as a plugin , Vue.use(VueFusionCharts, FusionCharts, ...otherDependencies), i think that will help

Yes, I solve it that way, but it would be good if we could use it as a component.

**Comment by ashok1994** [comment]
@StefanT123  I ll create an issue for that , will incorporate in next minor release

**Comment by ashok1994** [comment]
Closing for now
