### ISSUE TITLE
Module not found: Error: Can't resolve 'fusioncharts', appearing in the latest version of vue-fusioncharts

### ISSUE THREAD

**Issue by Dip686** [fusioncharts/vue-fusioncharts#59]
Module not found: Error: Can't resolve 'fusioncharts', appearing in the latest version of vue-fusioncharts. Seems we need to install it separately.

**Comment by rohanoid5** [comment]
@Dip686 you do need to install `FusionCharts` separately, it is mentioned in the [README](https://github.com/fusioncharts/vue-fusioncharts#requirements). Check the requirements.

Closing this.
